package com.giscafer.physicaltable.model;

import com.giscafer.physicaltable.model.base.BaseReportcard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reportcard extends BaseReportcard<Reportcard> {
	public static final Reportcard dao = new Reportcard();
}
