package com.giscafer.physicaltable.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReportcard<M extends BaseReportcard<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAge(java.lang.Integer age) {
		set("age", age);
	}

	public java.lang.Integer getAge() {
		return get("age");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public void setStudentId(java.lang.Integer studentId) {
		set("studentId", studentId);
	}

	public java.lang.Integer getStudentId() {
		return get("studentId");
	}

	public void setLdtyGrade(java.lang.Float ldtyGrade) {
		set("ldty_grade", ldtyGrade);
	}

	public java.lang.Float getLdtyGrade() {
		return get("ldty_grade");
	}

	public void setLdtyScore(java.lang.Float ldtyScore) {
		set("ldty_score", ldtyScore);
	}

	public java.lang.Float getLdtyScore() {
		return get("ldty_score");
	}

	public void setQcjspGrade(java.lang.Float qcjspGrade) {
		set("qcjsp_grade", qcjspGrade);
	}

	public java.lang.Float getQcjspGrade() {
		return get("qcjsp_grade");
	}

	public void setQcjspScore(java.lang.Float qcjspScore) {
		set("qcjsp_score", qcjspScore);
	}

	public java.lang.Float getQcjspScore() {
		return get("qcjsp_score");
	}

	public void setZfpGrade(java.lang.Float zfpGrade) {
		set("zfp_grade", zfpGrade);
	}

	public java.lang.Float getZfpGrade() {
		return get("zfp_grade");
	}

	public void setZfpScore(java.lang.Float zfpScore) {
		set("zfp_score", zfpScore);
	}

	public java.lang.Float getZfpScore() {
		return get("zfp_score");
	}

	public void setYwqzGrade(java.lang.Float ywqzGrade) {
		set("ywqz_grade", ywqzGrade);
	}

	public java.lang.Float getYwqzGrade() {
		return get("ywqz_grade");
	}

	public void setYwqzScore(java.lang.Float ywqzScore) {
		set("ywqz_score", ywqzScore);
	}

	public java.lang.Float getYwqzScore() {
		return get("ywqz_score");
	}

	public void setZpdjtmgGrade(java.lang.Float zpdjtmgGrade) {
		set("zpdjtmg_grade", zpdjtmgGrade);
	}

	public java.lang.Float getZpdjtmgGrade() {
		return get("zpdjtmg_grade");
	}

	public void setZpdjtmgScore(java.lang.Float zpdjtmgScore) {
		set("zpdjtmg_score", zpdjtmgScore);
	}

	public java.lang.Float getZpdjtmgScore() {
		return get("zpdjtmg_score");
	}

	public void setSytsGrade(java.lang.Float sytsGrade) {
		set("syts_grade", sytsGrade);
	}

	public java.lang.Float getSytsGrade() {
		return get("syts_grade");
	}

	public void setSytsScore(java.lang.Float sytsScore) {
		set("syts_score", sytsScore);
	}

	public java.lang.Float getSytsScore() {
		return get("syts_score");
	}

	public void setTqqGrade(java.lang.Float tqqGrade) {
		set("tqq_grade", tqqGrade);
	}

	public java.lang.Float getTqqGrade() {
		return get("tqq_grade");
	}

	public void setTqqScore(java.lang.Float tqqScore) {
		set("tqq_score", tqqScore);
	}

	public java.lang.Float getTqqScore() {
		return get("tqq_score");
	}

	public void setTqsstscqGrade(java.lang.Float tqsstscqGrade) {
		set("tqsstscq_grade", tqsstscqGrade);
	}

	public java.lang.Float getTqsstscqGrade() {
		return get("tqsstscq_grade");
	}

	public void setTqsstscqScore(java.lang.Float tqsstscqScore) {
		set("tqsstscq_score", tqsstscqScore);
	}

	public java.lang.Float getTqsstscqScore() {
		return get("tqsstscq_score");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

}
